apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodelayers-simple-apps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodelayers-simple-apps
    app.kubernetes.io/part-of: simple-apps
  name: nodelayers-simple-apps
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodelayers-simple-apps
status:
  loadBalancer: {}
